on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        
      - name: create-new-branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "New release: ${{ steps.package-version.outputs.current-version }}"
          branch: ${{ steps.package-version.outputs.current-version }}
          repository: .

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      
      # - run: git config advice.addIgnoredFile false

      - run: rm .gitignore
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_user_name: github-actions
          commit_user_email: noreply@arnaud.tech
          commit_author: github-actions <noreply@arnaud.tech>
          commit_message: "Remove .gitignore"
          skip_dirty_check: true
          push_options: '--force'
          create_branch: true
          branch: ${{ steps.package-version.outputs.current-version }}
          file_pattern: ./.gitignore

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated build files
          commit_options: '--no-verify'
          commit_user_name: github-actions
          commit_user_email: noreply@arnaud.tech
          commit_author: github-actions <noreply@arnaud.tech>
          file_pattern: ./index.min.js ./index.min.js.map ./package-lock.json
          skip_dirty_check: true
          push_options: '--force'
          branch: ${{ steps.package-version.outputs.current-version }}
          create_branch: true
          tagging_message: v${{ steps.package-version.outputs.current-version }}

  publish-github-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.package-version.outputs.current-version }}
      - name: create-new-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            index.min.js
            index.min.js.map
            package-lock.json
          tag_name: ${{ steps.package-version.outputs.current-version }}
          name: ${{ steps.package-version.outputs.current-version }}
          body: |
            Release ${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: false

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.package-version.outputs.current-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm config set access public
      - run: npm publish --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.package-version.outputs.current-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}